# -*- coding: utf-8 -*-
"""html_jju.text

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ixuQkZoXgME0lh2BerbE-ZWI8f07IIV
"""

html_text = """
<!doctype html>
<!--(if target build)>
    <html ng-app="angular" manifest="{{manifest}}.manifest">
<!(endif)-->
<!--(if target local)> -->
<html lang="ko">
<!--<!(endif)-->

<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-PQKJ9JE3BK"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-PQKJ9JE3BK');
    </script>
    <title>전주대학교 도서관</title>
    <meta charset="utf-8">
    <meta http-equiv='x-ua-compatible' content='ie=edge'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="./assets/css/ui.css"/>
    <link rel="stylesheet" href="./assets/css/main.css?sv=2024.9.19.10">
    <link rel="icon" href="./assets/images/jj/favicon.ico" type="image/x-icon">

    <!-- <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=fb4c7dadec790daffaa64e2aacf06a03"></script> -->
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=ef0573dc49cdc287dfc5d751f8cd3578"></script>
</head>

<body data-ng-controller="GlobalController">
<div data-ui-view class="ikc-pyxis-wrap"></div>

<script src="require.js"></script>

<script src="main.js?v=2024.9.19.10"></script>

</body>

</html>
"""

from langchain.text_splitter import RecursiveCharacterTextSplitter

# 파일 객체 생성 및 내용을 읽어서 변수에 저장
with open('/content/drive/MyDrive/Colab Notebooks/JJU/html_jju.text', 'r', encoding='utf-8') as f:
    file_content = f.read()

# 텍스트 분할기 생성
html_splitter = RecursiveCharacterTextSplitter(
    chunk_size=60,  # 청크 크기를 60으로 설정
    chunk_overlap=0  # 청크 간 중복되는 부분이 없도록 설정
)

# 주어진 HTML 텍스트를 분할하여 문서 생성
html_docs = html_splitter.split_text(file_content)

# 생성된 문서 출력
for doc in html_docs:
    print(doc)